# Generated by Django 3.2.9 on 2021-11-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcli', models.IntegerField(max_length=30)),
                ('nomecli', models.CharField(max_length=150)),
                ('enderecocli', models.CharField(max_length=300)),
                ('telefonecli', models.CharField(max_length=30)),
                ('emailcli', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codmed', models.IntegerField(max_length=30)),
                ('nomemed', models.CharField(max_length=150)),
                ('generomed', models.CharField(max_length=30)),
                ('telefonemed', models.CharField(max_length=30)),
                ('emailmed', models.EmailField(max_length=30)),
                ('codespecmed', models.IntegerField(max_length=30)),
            ],
        ),
    ]
