# Generated by Django 3.2.9 on 2021-11-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appiaad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicaMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcli', models.IntegerField()),
                ('codmed', models.IntegerField()),
                ('dataingresso', models.DateField()),
                ('cargahorariasemanal', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcli', models.IntegerField()),
                ('codmed', models.IntegerField()),
                ('cpfpaciente', models.IntegerField()),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codespec', models.IntegerField()),
                ('nomeespec', models.CharField(max_length=300)),
                ('descricao', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpfpac', models.IntegerField()),
                ('nomepac', models.CharField(max_length=300)),
                ('datanascimentopac', models.DateField()),
                ('generopac', models.CharField(max_length=300)),
                ('telefonepac', models.CharField(max_length=300)),
                ('emailpac', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='clinica',
            name='codcli',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='emailcli',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='nomecli',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='telefonecli',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='medico',
            name='codespecmed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medico',
            name='codmed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medico',
            name='emailmed',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='medico',
            name='generomed',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nomemed',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefonemed',
            field=models.CharField(max_length=300),
        ),
    ]
