# Generated by Django 3.2.9 on 2021-11-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLINICA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodCli', models.CharField(max_length=3)),
                ('NomeCli', models.CharField(max_length=130)),
                ('Endereco', models.CharField(max_length=130)),
                ('Telefone', models.CharField(max_length=11)),
                ('Email', models.CharField(max_length=130)),
            ],
        ),
    ]
