# Generated by Django 3.2.9 on 2021-12-04 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLINICA',
            fields=[
                ('CodCli', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('NomeCli', models.CharField(max_length=130)),
                ('Endereco', models.CharField(max_length=130)),
                ('Telefone', models.CharField(max_length=11)),
                ('Email', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='ESPECIALIDADE',
            fields=[
                ('CodEspec', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('NomeEspec', models.CharField(max_length=130)),
                ('Descricao', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='PACIENTE',
            fields=[
                ('CpfPaciente', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('NomePac', models.CharField(max_length=130)),
                ('DataNascimento', models.DateField()),
                ('Genero', models.CharField(max_length=1)),
                ('Telefone', models.CharField(max_length=11)),
                ('Email', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='MEDICO',
            fields=[
                ('CodMed', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('NomeMed', models.CharField(max_length=130)),
                ('Genero', models.CharField(max_length=1)),
                ('Telefone', models.CharField(max_length=11)),
                ('Email', models.CharField(max_length=130)),
                ('CodEspec', models.ForeignKey(max_length=3, on_delete=django.db.models.deletion.CASCADE, to='app.especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='CLINICAMEDICO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataIngresso', models.DateField()),
                ('CargaHorariaSemanal', models.CharField(max_length=3)),
                ('CodCli', models.ForeignKey(max_length=3, on_delete=django.db.models.deletion.CASCADE, to='app.clinica')),
                ('CodMed', models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='app.medico')),
            ],
        ),
        migrations.CreateModel(
            name='AGENDACONSULTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField()),
                ('CodCli', models.ForeignKey(max_length=3, on_delete=django.db.models.deletion.CASCADE, to='app.clinica')),
                ('CodMed', models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='app.medico')),
                ('CpfPaciente', models.ForeignKey(max_length=11, on_delete=django.db.models.deletion.CASCADE, to='app.paciente')),
            ],
        ),
    ]
